# vim:ft=kitty
## name: Bogster (Dark)
## license: MIT
## author: lhs
## upstream: https://github.com/vv9k/bogster
## blurb: A warm, muted dark theme with earthy, cozy vibes

#: The basic colors
foreground                      #c6bfba
background                      #161c23
selection_foreground            #d2c6b8
selection_background            #252f3b

#: Cursor colors
cursor                          #dfd7d0
cursor_text_color               #161c23

#: URL underline color when hovering with mouse
url_color                       #6fcc4c

#: kitty window border colors and terminal bell colors
active_border_color             #59dcb7
inactive_border_color           #313f4e
bell_border_color               #dc7759
visual_bell_color               none

#: OS Window titlebar colors
wayland_titlebar_color          system
macos_titlebar_color            system

#: Tab bar colors
active_tab_background           #161c23
active_tab_foreground           #dfd7d0
inactive_tab_background         #232d38
inactive_tab_foreground         #d2c6b8
tab_bar_background              #161c23
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)
mark1_foreground                #161c23
mark1_background                #23a580
mark2_foreground                #161c23
mark2_background                #cca734
mark3_foreground                #161c23
mark3_background                #b759dc

#: The basic 16 colors

#: black
color0                          #161c23
color8                          #45576d

#: red
color1                          #bd2853
color9                          #db567c

#: green
color2                          #549d2f
color10                         #6fcc4c

#: yellow
color3                          #cca734
color11                         #dfc26b

#: blue
color4                          #248baa
color12                         #4fbadb

#: magenta
color5                          #b759dc
color13                         #dc59c0

#: cyan
color6                          #23a580
color14                         #59dcb7

#: white
color7                          #c6bfba
color15                         #dfd7d0
