# vim:ft=kitty
## name: Bogster (Dark)
## license: MIT
## author: lhs
## upstream: https://github.com/vv9k/bogster
## blurb: A warm, muted dark theme with earthy, cozy vibes

#: The basic colors
foreground                      #c6b8ad
background                      #161c23
selection_foreground            #b6b6c9
selection_background            #2d3946

#: Cursor colors
cursor                          #e5ded6
cursor_text_color               #161c23

#: URL underline color when hovering with mouse
url_color                       #59dcb7

#: kitty window border colors and terminal bell colors
active_border_color             #7fdc59
inactive_border_color           #313f4e
bell_border_color               #dc7759
visual_bell_color               none

#: OS Window titlebar colors
wayland_titlebar_color          system
macos_titlebar_color            system

#: Tab bar colors
active_tab_background           #161c23
active_tab_foreground           #e5ded6
inactive_tab_background         #232d38
inactive_tab_foreground         #b6b6c9
tab_bar_background              #161c23
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)
mark1_foreground                #161c23
mark1_background                #59dcb7
mark2_foreground                #161c23
mark2_background                #dcb659
mark3_foreground                #161c23
mark3_background                #b759dc

#: The basic 16 colors

#: black
color0                          #161c23
color8                          #5a738c

#: red
color1                          #d32c5d
color9                          #dc597f

#: green
color2                          #57a331
color10                         #7fdc59

#: yellow
color3                          #dcb659
color11                         #e5c86b

#: blue
color4                          #36b2d4
color12                         #5bcceb

# #: magenta
color5                          #b759dc
color13                         #d393ea

#: cyan
color6                          #59dcb7
color14                         #7cebc9

#: white
color7                          #c6b8ad
color15                         #e5ded6
