# vim:ft=kitty

## name: Clockwork Gold
## author: Sonja Leaf, Clockwork
## license: MIT
## upstream: https://raw.githubusercontent.com/ClockworkNet/clockwork-gold/main/kitty/Clockwork_Gold.conf
## blurb: A dark, Monokai-descended theme on a warm near-black, built on
## clockwork.com's #FFCC00 gold.

#: The basic colors

foreground                      #ebe8e0
background                      #1d1c19
selection_foreground            #fcfaf4
selection_background            #4c4b47

#: Cursor colors

cursor                          #ffcc00
cursor_text_color               #1d1c19

#: URL underline color when hovering with mouse

url_color                       #4fa3f4

#: kitty window border colors and terminal bell colors

active_border_color             #ffcc00
inactive_border_color           #43423e
bell_border_color               #e94b4a

#: Tab bar colors

active_tab_foreground           #1d1c19
active_tab_background           #ffcc00
inactive_tab_foreground         #a9a69d
inactive_tab_background         #2c2b27
tab_bar_background              #2c2b27

#: The basic 16 colors

#: black
color0  #1d1c19
color8  #4c4b47

#: red
color1  #e94b4a
color9  #ff716b

#: green
color2  #73c881
color10 #88e196

#: yellow
color3  #ffcc00
color11 #c89f00

#: blue
color4  #4fa3f4
color12 #76c0ff

#: magenta
color5  #ef3ead
color13 #ff68c6

#: cyan
color6  #64c3c3
color14 #82e1e0

#: white
color7  #a9a69d
color15 #fcfaf4
