# vim:ft=kitty

## name: ferra
## author: eureka-cpu · https://github.com/eureka-cpu
## license: MIT
## upstream: https://github.com/casperstorm/ferra
## blurb: A warm, dark theme inspired by Kanagawa and Gruvbox.

# The cursor color
cursor #fecdb2

# The foreground color
foreground #fecdb2

# The background color
background #2b292d

# The foreground for selections
selection_foreground #fecdb2

# The background for selections
selection_background #4d424b

# The 16 terminal colors. There are 8 basic colors, each color has a dull and
# bright version.

# black
color0   #1f1e20
color8   #6f5d63

# red
color1   #c05862
color9   #e06b75

# green
color2   #8e9478
color10  #b1b695

# yellow
color3   #ffa07a
color11  #b8864e

# blue
color4   #bfbfcf
color12  #d1d1e0

# magenta
color5   #f6b6c9
color13  #e8829c

# cyan
color6   #8eb5b0
color14  #aacdc8

# white
color7   #d8d4d6
color15  #e4e0e2

active_tab_foreground   #fecdb2
active_tab_background   #383539
inactive_tab_foreground #d4a882
inactive_tab_background #2b292d
