# vim:ft=kitty

## name: GrokNight
## author: Bijan Rahnema
## license: Apache-2.0
## blurb: Grok dark palette from xai-org/grok-build. Tokyo Night accents
## on a neutral gray base.

#: The basic colors

foreground              #e1e1e1
background              #0a0a0a
selection_foreground    #e1e1e1
selection_background    #323237

#: Cursor colors

cursor                  #bb9af7
cursor_text_color       #0a0a0a

#: Tab bar colors

active_tab_foreground   #0a0a0a
active_tab_background   #bb9af7
inactive_tab_foreground #6c6c6c
inactive_tab_background #111111
tab_bar_background      #0a0a0a

#: The basic 16 colors

#: black
color0  #111111
color8  #6c6c6c

#: red
color1  #f7768e
color9  #f7768e

#: green
color2  #9ece6a
color10 #8bc34a

#: yellow
color3  #e0af68
color11 #ff9e64

#: blue
color4  #7aa2f7
color12 #7aa2f7

#: magenta
color5  #bb9af7
color13 #9d7cd8

#: cyan
color6  #1abc9c
color14 #3a95ab

#: white
color7  #c8c8c8
color15 #e1e1e1
