# vim:ft=kitty

## name: GrokDay
## author: Bijan Rahnema
## license: Apache-2.0
## blurb: Grok light palette from xai-org/grok-build. ANSI white is a dark
## gray so punctuation drawn as white stays readable.

#: The basic colors

foreground              #262626
background              #f5f5f5
selection_foreground    #262626
selection_background    #d4d4d8

#: Cursor colors

cursor                  #7d4bc6
cursor_text_color       #f5f5f5

#: Tab bar colors

active_tab_foreground   #f5f5f5
active_tab_background   #7d4bc6
inactive_tab_foreground #767676
inactive_tab_background #eaeaea
tab_bar_background      #f5f5f5

#: The basic 16 colors

#: black
color0  #262626
color8  #767676

#: red
color1  #cd3048
color9  #cd3048

#: green
color2  #378e23
color10 #4caf50

#: yellow
color3  #a27612
color11 #c3691e

#: blue
color4  #2f64d2
color12 #2f64d2

#: magenta
color5  #7d4bc6
color13 #6c3eb2

#: cyan
color6  #0a8e70
color14 #0f87a2

#: white
color7  #444444
color15 #262626
