# vim:ft=kitty

## name: Heetch Dark
## author: hackinister (https://github.com/hackinister)
## lincense: MIT
## blurp: Adaption of the WezTerm theme Heetch Dark
## created by Geoffrey Teale (https://github.com/tealeg/base16-heetch-scheme).

#: The basic colors

foreground                      #bdb6c5
background                      #190134
selection_foreground            #190134
selection_background            #bdb6c5

#: Cursor colors

cursor                          #bdb6c5
cursor_text_color               #190134

#: URL underline color when hovering with mouse

url_color                        #27d9d5

#: kitty window border colors and terminal bell colors

active_border_color              #feffff
inactive_border_color            #bdb6c5

#: Tab bar colors

active_tab_foreground           #190134
active_tab_background           #27d9d5
inactive_tab_foreground         #190134
inactive_tab_background         #7b6d8b
tab_bar_background              none
tab_bar_margin_color            none

#: The basic 16 colors

#: black
color0  #190134
color8  #7b6d8b

#: red
color1  #27d9d5
color9  #27d9d5

#: green
color2  #c33678
color10 #c33678

#: yellow
color3  #8f6c97
color11 #8f6c97

#: blue
color4  #bd0152
color12 #bd0152

#: magenta
color5  #82034c
color13 #82034c

#: cyan
color6  #f80059
color14 #f80059

#: white
color7  #bdb6c5
color15 #feffff


color16 #5ba2b6
color17 #470546
color18 #392551
color19 #5a496e
color20 #9c92a8
color21 #dedae2
