# vim:ft=kitty

## name: Linh
## author: cungun (https://github.com/cungun)
## license: MIT
## upstream: https://raw.githubusercontent.com/cungun/kitty-themes/refs/heads/linh/themes/Linh.conf  
## blurb: A dark theme w/ a light-blue foreground.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground #6ebefe
background #232323
selection_foreground #F3F4F4
selection_background #555555

#: Cursor colors

cursor #D6D6D6
cursor_trail_color none
#: cursor_text_color undefined 


#: URL underline color when hovering with mouse

# url_color undefined


#: kitty window border colors and terminal bell colors

# active_border_color undefined
# inactive_border_color undefined
# bell_border_color undefined
# visual_bell_color undefined


#: OS Window titlebar colors

# wayland_titlebar_color undefined
# macos_titlebar_color undefined


#: Tab bar colors

active_tab_foreground #444444
active_tab_background #c1ddff
inactive_tab_foreground #c8c8c8
inactive_tab_background #282828
# tab_bar_background undefined
# tab_bar_margin_color undefined


#: The basic 16 colors

#: black
color0 #555555
color8 #717171

#: red
color1 #C56360
color9 #E95752

#: green
color2 #599B5C
color10 #49AE4D

#: yellow
color3 #B2B05B
color11 #D8D54F

#: blue
color4 #B26CB7
color12 #CE70D4

#: magenta
color5 #7D7EB3
color13 #7374CA

#: cyan
color6 #50BBBC
color14 #57DCDD

#: white
color7 #D6D6D6
color15 #F3F4F4


#: You can set the remaining 240 colors as color16 to color255.
