# vim:ft=kitty
#: Retrowave Light by BrokenSideViewMirror

## name: Retrowave Light
## author: BrokenSideViewMirror (https://github.com/BrokenSideViewMirror)
## license: MIT
## upstream: https://github.com/BrokenSideViewMirror/themes-lair/blob/main/themes/Retrowave/retrowave-light.conf
## blurb: Retrowave Light is a light mode theme that takes inspiration from the vintage colors of the mid-to-late '90s! If you would like the dark mode version, refer to Retrowave Dark.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #5c4b51
background                      #f2ebbf
selection_foreground            #f2ebbf
selection_background            #5c4b51


#: Cursor colors

cursor                          #5c4b51
cursor_text_color               #f2eebf
cursor_trail_color              #1c6470


#: URL underline color when hovering with mouse

url_color                       #1c6470


#: kitty window border colors and terminal bell colors

active_border_color             #1c6470
inactive_border_color           #9c4e27
bell_border_color               #7f5814
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #fcf8de
macos_titlebar_color            #fcf8de


#: Tab bar colors

active_tab_foreground           #f2ebbf
active_tab_background           #1c6470
inactive_tab_foreground         #f2ebbf
inactive_tab_background         #5c4b51
tab_bar_background              #a8a588
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground #f2ebbf
mark1_background #1c6470
mark2_foreground #f2ebbf
mark2_background #7f5814
mark3_foreground #5c4b51 
mark3_background #fcf8de


#: The basic 16 colors

#: black
color0 #bfba9c
color8 #9b977f

#: red
color1 #9c4e27
color9 #68341a

#: green
color2  #788663
color10 #4e5641

#: yellow
color3  #9b6d18
color11 #7a5512

#: blue
color4  #1c6470
color12 #113f47

#: magenta
color5  #a31b42
color13 #681a30

#: cyan
color6  #4a8e7c
color14 #2d5b4f

#: white
color7  #5c4b51
color15 #3d3135


#: You can set the remaining 240 colors as color16 to color255.
