# vim:ft=kitty
#: Retrowave Dark by BrokenSideViewMirror

## name: Retrowave Dark
## author: BrokenSideViewMirror (https://github.com/BrokenSideViewMirror)
## license: MIT
## upstream: https://github.com/BrokenSideViewMirror/themes-lair/blob/main/themes/Retrowave/retrowave-dark.conf
## blurb: Retrowave Dark is a theme that I have mainly based off of the more vivid vintage age of colors. It is vivid and saturated with a defined palette.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #f3b562
background                      #5c4b51
selection_foreground            #5c4b51
selection_background            #f2ebbf


#: Cursor colors

cursor                          #8cbeb2
cursor_text_color               #5c4b51
cursor_trail_color              #f06060


#: URL underline color when hovering with mouse

url_color                       #8cbeb2


#: kitty window border colors and terminal bell colors

active_border_color             #f06060
inactive_border_color           #8cbeb2
bell_border_color               #f3b562
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #2d2528
macos_titlebar_color            #2d2528


#: Tab bar colors

active_tab_foreground           #5c4b51
active_tab_background           #8cbeb2
inactive_tab_foreground         #5c4b51
inactive_tab_background         #f2ebbf
tab_bar_background              #2d2528
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground #5c4b51
mark1_background #8cbeb2
mark2_foreground #5c4b51
mark2_background #f3b562
mark3_foreground #f2ebbf 
mark3_background #32231f


#: The basic 16 colors

#: black
color0 #7c676f
color8 #967e86

#: red
color1 #f06060
color9 #fc8f8f

#: green
color2  #a5d164
color10 #c1ef7c

#: yellow
color3  #f3b562
color11 #fcd29c

#: blue
color4  #6a9fd8
color12 #89bdf4

#: magenta
color5  #ed80b1
color13 #fcabd0

#: cyan
color6  #8cbeb2
color14 #aee2d6

#: white
color7  #f2ebbf
color15 #fcf8de


#: You can set the remaining 240 colors as color16 to color255.
