# vim:ft=kitty
#: School Boy Mono Dark by BrokenSideViewMirror.
#: Note that this is under the MIT license, which is approved by the FSF. This means that you may have the right to use, copy, modify, merge, publish, distribute, sublicense, or sell copies of this software for any purpose. However, the copyright notice and the permission notice must be included in all copies.

## name: School Boy Mono Dark
## author: BrokenSideViewMirror (https://github.com/BrokenSideViewMirror)
## license: MIT
## upstream: https://github.com/BrokenSideViewMirror/themes-lair/blob/main/themes/School-Boy/school-boy-mono.conf
## blurb: Absolutely HATE colored chalk but still want that school board aesthetic? This version of School Boy is for you! Unlike Colored, it is a monotone of green and white with colors staying constant.

#: The basic colors

foreground                      #bfbfbf
background                      #0b230a
selection_foreground            #0b230a
selection_background            #bfbfbf


#: Cursor colors

cursor                          #a3a3a3
cursor_text_color               #0b230a
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #dddddd


#: kitty window border colors and terminal bell colors

active_border_color             #dddddd
inactive_border_color           #194f17
bell_border_color               #dddddd
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #0b230a
active_tab_background           #bfbfbf
inactive_tab_foreground         #bfbfbf
inactive_tab_background         #256d23
tab_bar_background              #174715
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground #0b230a
mark1_background #bfbfbf
mark2_foreground #0b230a
mark2_background #bfbfbf
mark3_foreground #0b230a
mark3_background #bfbfbf


#: The basic 16 colors

#: black
color0 #174715
color8 #21631e

#: red
color1 #bfbfbf
color9 #dddddd

#: green
color2  #bfbfbf
color10 #dddddd

#: yellow
color3  #bfbfbf
color11 #dddddd

#: blue
color4  #bfbfbf
color12 #dddddd

#: magenta
color5  #bfbfbf
color13 #dddddd

#: cyan
color6  #bfbfbf
color14 #dddddd

#: white
color7  #bfbfbf
color15 #dddddd


#: You can set the remaining 240 colors as color16 to color255.
