# vim:ft=kitty
## name: Sequoia Retro Light
## author: Micheal Andreuzza
## license: MIT
## upstream: https://raw.githubusercontent.com/Sequoia-Theme/kitty/main/sequoia-retro-light.conf
## blurb: Sequoia Retro Light from the Sequoia theme family.

background #edeef2
foreground #282930
cursor #456a82
selection_background #817c9c38
selection_foreground #282930
color0 #d4d5dc
color1 #5f7982
color2 #4a704e
color3 #bf5238
color4 #456a82
color5 #c99730
color6 #8a6539
color7 #282930
color8 #42434e
color9 #c99730
color10 #4a704e
color11 #bf5238
color12 #456a82
color13 #5f7982
color14 #8a6539
color15 #282930
