# vim:ft=kitty
## name: Sequoia Moonlight Light
## author: Micheal Andreuzza
## license: MIT
## upstream: https://raw.githubusercontent.com/Sequoia-Theme/kitty/main/sequoia-moonlight-light.conf
## blurb: Sequoia Moonlight Light from the Sequoia theme family.

background #edeef2
foreground #282930
cursor #9a5fd9
selection_background #817c9c38
selection_foreground #282930
color0 #d4d5dc
color1 #c94da8
color2 #4a85d4
color3 #6a6a78
color4 #9a5fd9
color5 #282930
color6 #d9884a
color7 #282930
color8 #42434e
color9 #c94da8
color10 #4a85d4
color11 #6a6a78
color12 #9a5fd9
color13 #282930
color14 #d9884a
color15 #282930
