# vim:ft=kitty
## name: Serendipity Morning
## author: Micheal Andreuzza
## license: MIT
## upstream: https://raw.githubusercontent.com/Serendipity-Theme/kitty/main/serendipity-morning.conf
## blurb: Serendipity Morning from the Serendipity theme family.

background #f6f7fb
foreground #3f4363
cursor #6d7296
selection_background #5a567018
selection_foreground #3f4363
color0 #ccd0dc
color1 #c25a4d
color2 #2f7aab
color3 #785fd0
color4 #6288d8
color5 #629aa5
color6 #e58678
color7 #3f4363
color8 #505575
color9 #c25a4d
color10 #2f7aab
color11 #785fd0
color12 #6288d8
color13 #629aa5
color14 #e58678
color15 #3f4363
