# vim:ft=kitty
#: SynthWave '84 python (Ported from VS Code)

## name: SynthWave 84 python
## author: Dio Lin (Dionysus326)
## license: MIT
## blurb: A Python-optimized variant of the neon-soaked SynthWave '84 theme.
## Pro-tip: If 'ls' folder colors are unreadable
## add `export LS_COLORS="$LS_COLORS:ow=30;42"` to your .bashrc/.zshrc to make the text black.
## Ported from the VS Code theme by Skengrek.
## Original repository: https://gitlab.com/Skengrek/vscode-synthwave84-python

#: The basic colors
foreground              #ffade8
background              #100a24
selection_foreground    #ffffff
selection_background    #34294f

#: Cursor colors
cursor                  #03edf9
cursor_text_color       #100a24
cursor_trail_color      none

#: URL underline color when hovering with mouse
url_color               #ff7edb

#: kitty window border colors and terminal bell colors
active_border_color     #ff6c11
inactive_border_color   #2a2139
bell_border_color       #fe4450
visual_bell_color       none

#: OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

#: Tab bar colors
active_tab_foreground   #72f1b8
active_tab_background   #241b2f
inactive_tab_foreground #72f1b8
inactive_tab_background #100a24
tab_bar_background      none
tab_bar_margin_color    none

#: Colors for marks (marked text in the terminal)
mark1_foreground black
mark1_background #98d3cb
mark2_foreground black
mark2_background #f2dcd3
mark3_foreground black
mark3_background #f274bc

#: The basic 16 colors

#: black (Derived from UI elements as it wasn't explicitly in the terminal block)
color0 #2a2139
color8 #444251

#: red
color1 #ff2331
color9 #fe4450

#: green
color2  #37f39e
color10 #72f1b8

#: yellow
color3  #ffd83d
color11 #fede5d

#: blue
color4  #03edf9
color12 #03edf9

#: magenta
color5  #b30065
color13 #d40078

#: cyan
color6  #03edf9
color14 #03edf9

#: white (Derived from standard foregrounds)
color7  #dddddd
color15 #ffffff
