# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: T-Money
## author: Tytanium654
## license: GNU Public License, I assume? Do what you want with this, idc.
## upstream: https://github.com/Tytanium654/kitty-themes-tmoney/new/master/themes
## blurb: Didn't see a terminal theme I wanted. I decided to do it myself. I hope you like purple.
## This theme is meant to cater to my tastes and mine alone. But feel free to modify and make it your own! :)

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

# foreground                      #dddddd
# background                      #030017
# selection_foreground            #000000
# selection_background            #d1cdff


#: Cursor colors

# cursor                          #cccccc
# cursor_text_color               #3d6aff
# cursor_trail_color              none


#: URL underline color when hovering with mouse

# url_color                       #ff001e


#: kitty window border colors and terminal bell colors

# active_border_color             #3300ff
# inactive_border_color           #2b2dff
# bell_border_color               #ff001e
# visual_bell_color               none

#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

# active_tab_foreground           #1d0087
# active_tab_background           #070021
# inactive_tab_foreground         #444
# inactive_tab_background         #999
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #de0214
# mark2_foreground black
# mark2_background #026cde
# mark3_foreground black
# mark3_background #5e02de


#: The basic 16 colors

#: black
# color0 #000000
# color8 #767676

#: red
# color1 #ff0022
# color9 #ff0000

#: green
# color2  #19cb00
# color10 #23fd00

#: yellow
# color3  #cecb00
# color11 #fffd00

#: blue
# color4  #0026ff
# color12 #1a8fff

#: magenta
# color5  #7300ff
# color13 #fd28ff

#: cyan
# color6  #0dcdcd
# color14 #14ffff

#: white
# color7  #dddddd
# color15 #ffffff


#: You can set the remaining 240 colors as color16 to color255.
