## Vesper by theaaronn https://github.com/theaaronn

#: The basic colors

foreground                      #FFFFFF
background                      #000000
selection_foreground            #000000
selection_background            #ebb58c


#: Cursor colors

cursor                          #ebb58c
cursor_text_color               #000000
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #ebb58c


#: kitty window border colors and terminal bell colors

active_border_color             #ebb58c
inactive_border_color           #333333
bell_border_color               #ebb58c
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #FFFFFF
active_tab_background           #ebb58c
inactive_tab_foreground         #ebb58c
inactive_tab_background         #000000
tab_bar_background              none
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground black
mark1_background #ebb58c
mark2_foreground black
mark2_background #FFA500
mark3_foreground black
mark3_background #FF6600


#: The basic 16 colors

#: black
color0 #000000
color8 #333333

#: red
color1 #FF6600
color9 #ebb58c

#: green
color2  #ebb58c
color10 #FFA500

#: yellow
color3  #FFA500
color11 #FFB733

#: blue
color4  #ebb58c
color12 #FFA500

#: magenta
color5  #FF6600
color13 #ebb58c

#: cyan
color6  #FFA500
color14 #FFB733

#: white
color7  #FFFFFF
color15 #FFFFFF
