## name: Yotei Midnight
## author: Zenky
## license: MIT
## blurb: Yotei Midnight, inspired by a purple-red sky at dawn.

background #120D15
foreground #F2F2F2
cursor #E9E9F4
cursor_text_color #120D15
selection_background #44475A
selection_foreground #F2F2F2
url_color #CC65FF
active_border_color #FD4200
inactive_border_color #2F2635
bell_border_color #EA51B2
active_tab_background #120D15
active_tab_foreground #CC65FF
inactive_tab_background #0F0A12
inactive_tab_foreground #789EBB
tab_bar_background #0D0710

# ANSI colors: normal (0-7), bright (8-15).
color0 #282936
color1 #EA51B2
color2 #FD4200
color3 #77cdff
color4 #62D6E8
color5 #de71ff
color6 #A1EFE4
color7 #E9E9F4
color8 #626483
color9 #EA51B2
color10 #EBFF87
color11 #4351a1
color12 #e462e8
color13 #B45BCF
color14 #A1EFE4
color15 #F7F7FB
